### ISSUE TITLE
[7.4.10] del_row error

### ISSUE THREAD

**Issue by mattmull42** [ragardner/tksheet#275]
Hi,

I noticed that removing a row in `7.4.10` with `del_row` leads to an `AttributeError: 'MainTable' object has no attribute 'MT'`.
Here is a minimal code to reproduce the error:
```
import tkinter as tk
from tksheet import Sheet

data = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]

class Demo(tk.Tk):
    def __init__(self) -> None:
        super().__init__()

        self.sheet = Sheet(self, data=data)
        self.sheet.enable_bindings("single_select", "row_select", "right_click_popup_menu")
        self.sheet.popup_menu_add_command("Delete row", self.delete_row, False, True, False, False)

        self.sheet.pack()

        self.bind("<Control-q>", lambda _: self.destroy())
        self.mainloop()

    def delete_row(self) -> None:
        row_id = self.sheet.get_selected_rows().pop()
        self.sheet.del_row(row_id)

if __name__ == "__main__":
    Demo()
```

Here is the full error:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.12/tkinter/__init__.py", line 1971, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/user/code/demo.py", line 21, in delete_row
    self.sheet.del_row(row_id)
  File "/home/user/code/.venv/lib/python3.12/site-packages/tksheet/sheet.py", line 1819, in del_rows
    event_data = self.MT.delete_rows(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/code/.venv/lib/python3.12/site-packages/tksheet/main_table.py", line 5597, in delete_rows
    event_data = self.delete_rows_data(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/code/.venv/lib/python3.12/site-packages/tksheet/main_table.py", line 5520, in delete_rows_data
    elif isinstance(self.MT._row_index, list):
                    ^^^^^^^
AttributeError: 'MainTable' object has no attribute 'MT'
```

It works well in `7.4.9` however.
Anyway, many thanks for your work!

**Comment by ragardner** [comment]
Thanks for the report, should be fixed in 7.4.11
